### ISSUE TITLE
Hi there! 👋

### ISSUE THREAD

**Issue by chrisdmacrae** [n-dvo-tech/react-tinacms-sanity#3]
Hi there @n-dvo-tech!

My name is Chris and I'm the lead solution engineer at Forestry (TinaCMS).

Really excited to see this plugin, and was wondering if there's any help or assistance I can provide you.

I'd be happy to jump on a video chat if you'd prefer that, just to meet and talk shop.

Cheers,

Chris

**Comment by n-dvo-tech** [comment]
Hey @chrisdmacrae 
Definitely would like to catch up on a video chat. Let me know what times are available for you this week and we'll figure something out.

All the best!

Nate

**Comment by chrisdmacrae** [comment]
@n-dvo-tech sounds good Nate! Feel free to book me anytime Wednesday afternoon or later this week!

https://meetings.hubspot.com/chrisdmacrae/chat?_ga=2.154228413.441370135.1603119490-530488928.1603119490

**Comment by n-dvo-tech** [comment]
Thanks for the meeting @chrisdmacrae. We'll be in touch!
